version: '3.9'

services:
  database:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root321
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
